language: java

jdk:
 - oraclejdk8

os:
  - linux

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo "Skipping before script"

install:
  - echo "Skipping before script"

script:
  - ./gradlew build

after_success:
  - bash <(curl -s https://codecov.io/bash)